name: vygauss

plugins:
  - name: vyper
  - name: foundry

vyper:
  version: 0.4.0

default_ecosystem: ethereum

ethereum:
  default_network: local
  local:
    default_provider: foundry

contracts_folder: src
